//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyonProjesi.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTicariOtomasyonEntities : DbContext
    {
        public DbTicariOtomasyonEntities()
            : base("name=DbTicariOtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBLCARI> TBLCARIs { get; set; }
        public virtual DbSet<TBLCARIHAREKET> TBLCARIHAREKETs { get; set; }
        public virtual DbSet<TBLDEPARTMAN> TBLDEPARTMen { get; set; }
        public virtual DbSet<TBLFIRMA> TBLFIRMAs { get; set; }
        public virtual DbSet<TBLFIRMAHAREKET> TBLFIRMAHAREKETs { get; set; }
        public virtual DbSet<TBLGIDERLER> TBLGIDERLERs { get; set; }
        public virtual DbSet<TBLİLCELER> TBLİLCELER { get; set; }
        public virtual DbSet<TBLILLER> TBLILLERs { get; set; }
        public virtual DbSet<TBLKASA> TBLKASAs { get; set; }
        public virtual DbSet<TBLKATEGORI> TBLKATEGORIs { get; set; }
        public virtual DbSet<TBLNOTLAR> TBLNOTLARs { get; set; }
        public virtual DbSet<TBLPERSONEL> TBLPERSONELs { get; set; }
        public virtual DbSet<TBLURUN> TBLURUNs { get; set; }
    }
}
